from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import os
import json
import time
import requests
import unicodedata
from dotenv import load_dotenv

load_dotenv()

# Compute the hash required by the Iguana CMS for API Authentification
def hash_url(url):
    s = unicodedata.normalize("NFC", url)
    h = 305419896
    for i, c in enumerate(s):
        h += ord(c) * (i + 1)
    return str(h)


# Query the availability of a book by its record ID
def get_availability(record_id, api_token, cookies):
    parameters = f"?id=p::usmarcdef_{record_id}&locale=fr&aspect=Stock&opac=true"

    # The X-InMedia-Authorization header format was reverse engineered from the website JS.
    # It requires: "Bearer null <api_token> <hash_of_url_parameters>"
    # The api_token comes from window.mobileSettings.apiToken in the browser.
    inmedia = f"Bearer null {api_token} {hash_url(parameters)}"

    response = requests.get(
        f"https://catalogue.bm-lyon.fr/in/rest/api/notice{parameters}",
        headers={"X-InMedia-Authorization": inmedia, "X-microsite-id": "mainSite"},
        cookies=cookies
    )
    data = response.json()
    available_branches = []
    for copy in data.get("monographicCopies", []):
        for child in copy.get("children", []):
            d = child.get("data", {})
            if d.get("stat_desc") == "En rayon":
                branch = d.get("branch_desc")
                if branch and branch not in available_branches:
                    available_branches.append(branch)
    return available_branches

def get_meta(record_id, api_token, cookies):

    def get_field(fields, name):
        for field in fields:
            if field["name"] == name:
                return field["values"][0]["qa"]["Answer"]
        return("")

    parameters = f"?id=p::usmarcdef_{record_id}&locale=fr&aspect=Meta&opac=true"
    inmedia = f"Bearer null {api_token} {hash_url(parameters)}"
    response = requests.get(
        f"https://catalogue.bm-lyon.fr/in/rest/api/notice{parameters}",
        headers={"X-InMedia-Authorization": inmedia, "X-microsite-id": "mainSite"},
        cookies=cookies
    )
    data = response.json()
    fields = data.get("fields", [])
    title = get_field(fields, "title")
    title = title.split("[")[0]
    author = get_field(fields, "creator")
    author = author.split(", (")[0]
    date = get_field(fields, "dateIssuedYear")
    return {
        "title": title,
        "author": author,
        "date": date
    }


# --- Selenium setup ---
# We use Selenium to drive a real Firefox browser because the website is a React app.
# The page content (book list, api_token) is generated by JavaScript at runtime
# and cannot be retrieved with a simple HTTP request.
options = Options()
options.binary_location = os.getenv("LOC_FIREFOX")
options.set_preference('intl.accept_languages', 'fr-FR,fr')
driver = webdriver.Firefox(options=options)
wait = WebDriverWait(driver, 15)

# Login
driver.get("https://catalogue.bm-lyon.fr/account")
wait.until(EC.presence_of_element_located((By.ID, "loginField")))
driver.find_element(By.ID, "loginField").send_keys(os.getenv("BM_ID"))
driver.find_element(By.ID, "passwordField").send_keys(os.getenv("BM_PSW"))
driver.find_element(By.CSS_SELECTOR, "button[aria-label='Connexion']").click()
wait.until(EC.url_changes("https://catalogue.bm-lyon.fr/account"))

# Naviguate to the reading list
driver.get(f"https://catalogue.bm-lyon.fr/my/list/{os.getenv('BM_TBR_ID')}")
time.sleep(3)

# Extract book titles and ID
titles = driver.execute_script("""
    return [...document.querySelectorAll('[title]')]
        .filter(el => el.getAttribute('title').includes('[Livre]'))
        .map(el => el.getAttribute('title'))
        .filter((v, i, a) => a.indexOf(v) === i);
""")

ids = driver.execute_script("""
    return [...document.querySelectorAll('[style*="usmarcdef"]')]
        .map(el => el.style.backgroundImage.match(/usmarcdef_(\\d+)/)?.[1]);
""")

api_token = driver.execute_script("return window.mobileSettings.apiToken")
cookies = {c['name']: c['value'] for c in driver.get_cookies()}
driver.quit()

print(f"Liste récupérée : {len(ids)} BD")

# Check availability for each book
books = []
for i, (title, record_id) in enumerate(zip(titles, ids)):
    print(f"[{i+1}/{len(ids)}] {title[:40]}...")
    branches = get_availability(record_id, api_token, cookies)
    meta = get_meta(record_id, api_token, cookies)
    books.append({
        "title": meta["title"],
        "author": meta["author"],
        "date": meta["date"],
        "id": record_id,
        "available": len(branches) > 0,
        "branches": branches
    })
    time.sleep(0.01)

with open("books.json", "w", encoding="utf-8") as f:
    json.dump(books, f, ensure_ascii=False, indent=2)